package me.adilfulara.autoledger.domain.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * Car entity representing user vehicles for mileage tracking.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table("cars")
public class Car {

    /**
     * Unique identifier for the car.
     */
    @Id
    private UUID id;

    /**
     * Foreign key reference to users.id (internal UUID).
     */
    private UUID userId;

    /**
     * Car manufacturer (e.g., "Toyota", "Tesla").
     */
    private String make;

    /**
     * Car model (e.g., "Camry", "Model 3").
     */
    private String model;

    /**
     * Model year.
     */
    private Integer year;

    /**
     * Vehicle Identification Number (17 characters, optional).
     */
    private String vin;

    /**
     * User-friendly name for the car (e.g., "My Tesla", "Work Truck").
     */
    private String name;

    /**
     * Default unit for fuel volume.
     */
    private FuelUnit primaryFuelUnit;

    /**
     * Default unit for distance.
     */
    private DistanceUnit primaryDistanceUnit;

    /**
     * Timestamp when the car record was created.
     * Managed by Spring Data auditing.
     */
    @CreatedDate
    private Instant createdAt;

    /**
     * Timestamp when the car record was last updated.
     * Managed by Spring Data auditing.
     */
    @LastModifiedDate
    private Instant updatedAt;

    /**
     * Constructor for creating new cars (ID generated by database).
     */
    public Car(UUID userId, String make, String model, Integer year, String vin, String name,
               FuelUnit primaryFuelUnit, DistanceUnit primaryDistanceUnit) {
        this.userId = userId;
        this.make = make;
        this.model = model;
        this.year = year;
        this.vin = vin;
        this.name = name;
        this.primaryFuelUnit = primaryFuelUnit;
        this.primaryDistanceUnit = primaryDistanceUnit;
    }
}
