package me.adilfulara.autoledger.domain.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.relational.core.mapping.Table;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Fillup entity representing fuel purchase records.
 * Used for calculating MPG/fuel economy metrics.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table("fillups")
public class Fillup {

    /**
     * Unique identifier for the fillup.
     */
    @Id
    private UUID id;

    /**
     * Foreign key reference to cars.id.
     */
    private UUID carId;

    /**
     * Date and time of the fill-up.
     */
    private Instant date;

    /**
     * Total vehicle mileage/kilometers at fill-up.
     */
    private Long odometer;

    /**
     * Amount of fuel added.
     * Uses BigDecimal for precision (up to 3 decimal places).
     */
    private BigDecimal fuelVolume;

    /**
     * Unit for fuel volume (snapshotted from car at fillup time).
     * Preserves historical accuracy if car's unit settings change.
     */
    private FuelUnit fuelUnit;

    /**
     * Price per unit of fuel.
     * Uses BigDecimal for financial precision (up to 3 decimal places).
     */
    private BigDecimal pricePerUnit;

    /**
     * Total cost of fill-up (currency).
     * Uses BigDecimal for financial precision (up to 2 decimal places).
     */
    private BigDecimal totalCost;

    /**
     * Unit for odometer (snapshotted from car at fillup time).
     * Preserves historical accuracy if car's unit settings change.
     */
    private DistanceUnit distanceUnit;

    /**
     * TRUE if tank was not filled to top.
     * When true, MPG calculation should be skipped for this entry.
     */
    private Boolean isPartial;

    /**
     * TRUE if user missed logging previous fill-up.
     * When true, MPG calculation chain should be broken.
     */
    private Boolean isMissed;

    /**
     * Timestamp when the fillup record was created.
     * Managed by Spring Data auditing.
     */
    @CreatedDate
    private Instant createdAt;

    /**
     * Timestamp when the fillup record was last updated.
     * Managed by Spring Data auditing.
     */
    @LastModifiedDate
    private Instant updatedAt;

    /**
     * Constructor for creating new fillups (ID generated by database).
     * Units are auto-defaulted from car settings but stored on fillup for historical accuracy.
     */
    public Fillup(UUID carId, Instant date, Long odometer, BigDecimal fuelVolume,
                  FuelUnit fuelUnit, BigDecimal pricePerUnit, BigDecimal totalCost,
                  DistanceUnit distanceUnit, Boolean isPartial, Boolean isMissed) {
        this.carId = carId;
        this.date = date;
        this.odometer = odometer;
        this.fuelVolume = fuelVolume;
        this.fuelUnit = fuelUnit;
        this.pricePerUnit = pricePerUnit;
        this.totalCost = totalCost;
        this.distanceUnit = distanceUnit;
        this.isPartial = isPartial != null ? isPartial : false;
        this.isMissed = isMissed != null ? isMissed : false;
    }
}
