package me.adilfulara.autoledger.domain.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * User entity representing authenticated users.
 * Uses internal UUID for stable identity, decoupled from external auth provider.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table("users")
public class User {

    /**
     * Internal stable UUID (primary key).
     * Generated by database, never changes even if auth provider changes.
     */
    @Id
    private UUID id;

    /**
     * External identifier from auth provider (e.g., Clerk).
     * Example: "user_2abc123xyz"
     * Allows switching auth providers without losing user data.
     */
    private String authProviderId;

    /**
     * User's email address from auth provider.
     */
    private String email;

    /**
     * Timestamp when the user record was created.
     * Managed by Spring Data auditing.
     */
    @CreatedDate
    private Instant createdAt;

    /**
     * Constructor for creating new users.
     * ID and createdAt will be set by the database.
     */
    public User(String authProviderId, String email) {
        this.authProviderId = authProviderId;
        this.email = email;
    }
}
